# 8장. 핵심 키워드 추출 (Keyword Extraction)

# 8-0 데이터 준비

## Mecab 설치 (필요시)

In [ ]:
# !sudo apt-get install g++ openjdk-7-jdk # Install Java 1.7+
# !sudo apt-get install python-dev; pip install konlpy     # Python 2.x
# !sudo apt-get install python3-dev; pip3 install konlpy   # Python 3.x
# !sudo apt-get install curl
# !bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package openjdk-7-jdk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'openjdk-7-jdk' has no installation candidate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.15~rc1-1).
0 upgraded, 0 newly installed, 0 to remove and 81 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-dev is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 81 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.58.0-2ubuntu3.13).
0 upgraded, 0 newly installed, 0 to remove and 81 not upgraded.
mecab-ko i

# 8-1 TF-IDF 활용 핵심키워드 추출

## 실습 1. sklearn 활용


In [6]:
!pip list

Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-project                   0.9.1
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.5
astropy                            4.2.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.6
Babel                              2.9.0
backcall                           0.2.0
backports.shutil-get-terminal-size 1.0.0
bcrypt                             3.2.0
beautifulsoup4                     4.6.0
bitarray                           1.9.2
bkcharts                           0.2
black                              19.10b0

In [1]:
import requests
from bs4 import BeautifulSoup
import re

def get_news_by_url(url):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
    response = requests.get(url, headers=headers)

    html = response.text
    soup = BeautifulSoup(html, "html.parser")
    
    article = soup.select("div._article_body_contents")[0].text
    article = article.split('\n')[8]
    
    return article[:re.search("\w+@\w+\.\w+(.\w+)?",article).start()-1]
docs = []
docs.append(get_news_by_url('https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=105&oid=018&aid=0004430108') )
docs.append(get_news_by_url('https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=001&aid=0011614790') )
docs.append(get_news_by_url('https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=014&aid=0004424362') )
docs.append(get_news_by_url('https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=119&aid=0002402191') )
docs.append(get_news_by_url('https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=030&aid=0002882728') )
print(docs)


['과기정통부, 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입, 5100여종 데이터 구축민간 클라우드 통한 외부연계체계도.."개방성 강화"[이데일리 이재운 기자] 국가 차원의 빅데이터 활용 시대가 열린다. 새로운 산업 창출과 기존 산업의 변화에 이르는 ‘혁신성장’을 위한 센터가 문을 연다. 10개 분야에 걸쳐 ‘데이터 경제’의 발전을 위한 정부의 청사진을 현실로 구현하는데 앞장선다는 계획이다.22일 과학기술정보통신부는 서울 중구 대한상공회의소에서 데이터 생태계 조성과 혁신 성장의 기반 마련을 위한 ‘빅데이터 플랫폼 및 센터’ 출범식 행사를 개최했다. 유영민 과기정통부 장관을 비롯해 노웅래 국회 과학기술정보방송통신위원회 위원장 등 300여명이 참가했다.◇10개 분야 100개 센터..3년간 1516억원 투입이미지: 픽사베이빅데이터는 데이터 활용을 통해 혁신성장을 이루자는 문재인 정부의 경제 성장 핵심 요소중 하나다. 문재인 대통령이 직접 올 들어 데이터 활용과 이에 따른 정보보호(보안)에 대한 중요성을 강조하기도 했다.이런 맥락 속에서 빅데이터센터는 공공과 민간이 협업해 활용도 높은 양질의 데이터를 생산·구축하고, 플랫폼은 이를 수집·분석·유통하는 역할을 담당한다. 과기정통부는 분야별 플랫폼 10개소와 이와 연계된 기관별 센터 100개소를 구축하는데 3년간 총 1516억원을 투입할 계획이며, 올해 우선 640억원 규모의 사업을 추진하고 있다.대상 분야는 △금융(BC카드) △환경(한국수자원공사) △문화(한국문화정보원) △교통(한국교통연구원) △헬스케어(국립암센터) △유통·소비(매일방송) △통신(KT) △중소기업(더존비즈온) △지역경제(경기도청) △산림(한국임업진흥원) 등으로 현재 1차 공모를 통해 72개 빅데이터 센터를 선정했고, 다음달 8일까지 2차 공모를 통해 28개를 추가 선정해 총 100개를 지원, 운영할 계획이다. 이를 통해 데이터 생태계를 혁신하고 기업의 경쟁력을 제고하는 역할을 수행한다.주요 활용 전략·사례를 보면 빅데이터 활용을

### 1) 전처리

In [2]:

from konlpy.tag import Mecab
mecab = Mecab()
preprocessed_docs = []
for doc in docs:
    token_list = []
    for token in mecab.pos(doc):
        if token[1] in ['NNG', 'VV']:
            token_list.append(token[0])
    preprocessed_docs.append(" ".join(token_list))

preprocessed_docs[0][:100]

'과기 정통부 장관 참석 기념행사 투입 여종 데이터 구축 민간 외부 연계 체계 개방 강화 기자 국가 차원 빅 데이터 활용 시대 산업 창출 기존 산업 변화 이르 혁신 장 센터 문 분야'

In [3]:

from konlpy.tag import Mecab
import re
mecab = Mecab()
preprocessed_docs = []
for doc in docs:
    re_doc = re.sub('[^가-힣]', ' ', doc)
    pos_docs = mecab.pos(re_doc)
    preprocessed_docs.append(" ".join(mecab.nouns(re_doc)))

preprocessed_docs[0][:100]

'과기 정통부 일 유영민 장관 등 참석 기념행사 년 억 원 투입 여종 데이터 구축 민간 클라우드 외부 연계 체계 개방 강화 데일리 이재운 기자 국가 차원 빅 데이터 활용 시대 산업 '

'과기 정통부 일 유영민 장관 등 참석 기념행사 년 억 원 투입 여종 데이터 구축 민간 클라우드 통한 외부 연계 체계 개방 강화 데일리 이재운 기자 국가 차원 빅 데이터 활용 시대 '

In [4]:
mecab = Mecab()
for preprocessed_doc in preprocessed_docs:것..,
    print(mecab.pos(preprocessed_doc))

[('과기', 'NNG'), ('정통부', 'NNG'), ('일', 'NNG'), ('유영민', 'NNP'), ('장관', 'NNG'), ('등', 'NNB'), ('참석', 'NNG'), ('기념행사', 'NNG'), ('년', 'NNBC'), ('억', 'NR'), ('원', 'NNBC'), ('투입', 'NNG'), ('여종', 'NNG'), ('데이터', 'NNG'), ('구축', 'NNG'), ('민간', 'NNG'), ('클라우드', 'NNP'), ('외부', 'NNG'), ('연계', 'NNG'), ('체계', 'NNG'), ('개방', 'NNG'), ('강화', 'NNP'), ('데일리', 'NNP'), ('이재운', 'NNP'), ('기자', 'NNG'), ('국가', 'NNG'), ('차원', 'NNG'), ('빅', 'NNG'), ('데이터', 'NNG'), ('활용', 'NNG'), ('시대', 'NNG'), ('산업', 'NNG'), ('창출', 'NNG'), ('기존', 'NNG'), ('산업', 'NNG'), ('변화', 'NNG'), ('혁신', 'NNG'), ('장', 'NNG'), ('센터', 'NNG'), ('문', 'NNG'), ('개', 'NNBC'), ('분야', 'NNG'), ('데이터', 'NNG'), ('경제', 'NNG'), ('발전', 'NNG'), ('정부', 'NNG'), ('청사진', 'NNG'), ('현실', 'NNG'), ('구현', 'NNG'), ('데', 'NNB'), ('계획', 'NNG'), ('일', 'NR'), ('과학', 'NNG'), ('기술', 'NNG'), ('정보', 'NNG'), ('통신부', 'NNG'), ('서울', 'NNP'), ('중구', 'NNP'), ('대한', 'NNP'), ('상공', 'NNG'), ('회의소', 'NNG'), ('데이터', 'NNG'), ('생태', 'NNG'), ('조성', 'NNG'), ('혁신', 'NNG'), ('성장', 'NNG'), ('기반

### 2) TF-IDF 계산

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
count_vect = CountVectorizer(max_df=0.85, max_features=10000)
# count_vect = CountVectorizer()
# 0.85이상인거 뺀다, vocab를 10000개만 만든다.
word_count = count_vect.fit_transform(preprocessed_docs)
print(count_vect.get_feature_names()[:10])

['가공', '가능', '가입자', '가족', '가중치', '가치', '각종', '감소', '감염', '강국']


In [6]:
count_vect.fit(preprocessed_docs)

CountVectorizer(max_df=0.85, max_features=10000)

In [57]:
count_vect.get_feature_names()

['가공',
 '가능',
 '가입자',
 '가족',
 '가중치',
 '가치',
 '각종',
 '감소',
 '감염',
 '강국',
 '강원',
 '강조',
 '강화',
 '개년',
 '개발',
 '개방',
 '개선',
 '개소',
 '개인',
 '개최',
 '거버넌스',
 '건강',
 '건수',
 '검색',
 '결과',
 '결제',
 '경기',
 '경기도',
 '경우',
 '경쟁력',
 '경제',
 '경진',
 '계층',
 '계획',
 '고도',
 '공공',
 '공급',
 '공모',
 '공사',
 '공유',
 '공인',
 '과기',
 '과학',
 '관광',
 '관광지',
 '관람',
 '관련',
 '관리',
 '광주',
 '교통',
 '구성',
 '구축',
 '구현',
 '국가',
 '국내',
 '국립암센터',
 '국회',
 '규모',
 '그룹',
 '금리',
 '금융',
 '급물살',
 '기간',
 '기관',
 '기념행사',
 '기대',
 '기반',
 '기술',
 '기술원',
 '기업',
 '기여',
 '기점',
 '기존',
 '기준',
 '기초',
 '기회',
 '김종갑',
 '나주',
 '낙후',
 '남성',
 '노웅래',
 '논의',
 '누구',
 '눈길',
 '뉴스',
 '다각',
 '다음',
 '단계',
 '단지',
 '담당',
 '대구',
 '대국민',
 '대비',
 '대상',
 '대출',
 '대통령',
 '대한',
 '대한민국',
 '대형',
 '대회',
 '데일리',
 '데일리안',
 '도구',
 '도시',
 '도청',
 '동량',
 '동반',
 '등록',
 '레벨',
 '레저',
 '마련',
 '마켓',
 '맞춤',
 '매출',
 '맥락',
 '모델',
 '모바일',
 '모색',
 '모수',
 '문재',
 '문재인',
 '문제',
 '문제점',
 '문화',
 '미래',
 '미만',
 '민간',
 '반출',
 '발걸음',
 '발굴',
 '발생',
 '발전',
 '발표',
 '방문',
 '방송',
 '방안',
 '방침',
 '베이',
 '벤처',


['과기', '정통부', '유영민', '장관', '참석', '기념행사', '투입', '여종', '구축', '민간']

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(smooth_idf=True, use_idf=True)
tfidf_transformer.fit(word_count)

TfidfTransformer()

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)

### 3) 핵심키워드 추출

In [8]:
def sort_keywords(keywords):
    return sorted(zip(keywords.col, keywords.data), key=lambda x:(x[1], x[0]), reverse=True)
    

def extract_keywords(feature_names, sorted_keywords, n=5):
    """
    전체 키워드에 대한 상위 n개 획득한다.\n
    n에 대한 기본값 5
    """
    return [(feature_names[idx], score) for idx, score in sorted_keywords[:n]] 

In [9]:
doc = preprocessed_docs[0] # 핵심키워드 추출할 문서 조회

feature_names = count_vect.get_feature_names()
tfidf_vect = tfidf_transformer.transform(count_vect.transform([doc]))
sorted_keywords = sort_keywords(tfidf_vect.tocoo())

# 사용자가 지정한 갯수만큼 키워드 추출
keywords = extract_keywords(feature_names, sorted_keywords, 5)
 
print("\n===== 원문 =====")
print(docs[0][:100])
print("\n=== 핵심키워드 ===")
for k in keywords:
    print(k)


===== 원문 =====
과기정통부, 22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입, 5100여종 데이터 구축민간 클라우드 통한 외부연계체계도.."개방성 강화"[이데일리 이재운 기자

=== 핵심키워드 ===
('플랫', 0.25211725427472975)
('센터', 0.223203299489251)
('계획', 0.2161005036640541)
('활용', 0.18262088140029625)
('정통부', 0.18008375305337843)



---


## 실습 2. gensim 활용


### 1) 전처리

In [11]:
from konlpy.tag import Mecab
mecab = Mecab()

preprocessed_docs = []
for doc in docs :
  # 명사와 동사만으로 문서 전처리
  preprocessed_docs.append(' '.join([token[0] for token in mecab.pos(doc) if token[1][0] in ['N', 'V']]))
preprocessed_docs[0][:100]

'과기 정통부 일 유영민 장관 등 참석 기념행사 년 억 원 투입 여종 데이터 구축 민간 클라우드 통한 외부 연계 체계 개방 강화 데일리 이재운 기자 국가 차원 빅 데이터 활용 시대 '

### 2) TF-IDF 계산

In [39]:
# !pip install python-Levenshtein

In [40]:
from gensim.models import TfidfModel
from gensim.corpora import Dictionary

document_ls = [doc.split() for doc in preprocessed_docs]
dct = Dictionary(document_ls) # 인덱스(key) - 단어(valuue) 인 딕셔너리 생성
corpus = [dct.doc2bow(doc) for doc in document_ls] # 각 문서에 포함된 단어를 인덱스로 변환하여 corpus 생성
tfidf = TfidfModel(corpus) # TF-IDF 산출

### 3) 핵심키워드 추출

In [41]:
def sort_keywords(tfidf):
    return sorted(tfidf, key=lambda x: (x[1], x[0]), reverse=True)

def extract_keywords(feature_names, sorted_keywords, n=5):
    return [(feature_names[idx], score) for idx, score in sorted_keywords[:n]]

In [42]:
doc = corpus[0]

sorted_keywords = sort_keywords(tfidf[doc]) # TF-IDF를 기준으로 역순 정렬

# 사용자가 지정한 갯수만큼 키워드 추출
keywords = extract_keywords(dct, sorted_keywords, 5)

print("\n=== 핵심키워드 ===")
for k in keywords:
    print(k)


=== 핵심키워드 ===
('플랫', 0.2495222182663338)
('폼', 0.2495222182663338)
('계획', 0.21387618708542896)
('정통부', 0.17823015590452412)
('위한', 0.17823015590452412)


In [ ]:
tfidf[doc]



---



# 8-2 Textrank
https://web.eecs.umich.edu/~mihalcea/papers/mihalcea.emnlp04.pdf

<img src="https://3.bp.blogspot.com/-yp0Lr3ec5EY/XIs6znCcO_I/AAAAAAAAAPY/xtZxe_OYtH0xeuWsp4Qd4DQrunGMpVQmQCLcBGAs/s640/keyword-extraction-textrank.png" />

## 실습 1. 행렬 활용 


In [16]:
tokens = ['딸기', '바나나', '사과', '딸기', '파인애플']
nodes = ['바나나', '사과', '파인애플', '딸기']
vocab = nodes # set(token) 해도댐.


vocab2idx = {vocab[i]:i for i in range(0, len(vocab))} #vocab을 인덱스로 변환
idx2vocab = {i:vocab[i] for i in range(0, len(vocab))} #인덱스를 vocab으로 변환
vocab2idx

['바나나', '사과', '파인애플', '딸기']


{'바나나': 0, '사과': 1, '파인애플': 2, '딸기': 3}

### 3) 그래프 생성 (weighted edge 계산)

*   TextRank는 그래프 기반 모델
*   각 단어(토큰)은 그래프의 노드(vertex) 
*   weighted_edge 행렬은 노드간 가중치 정보를 담고 있음
*   weighted_edge[i][j] 는 i번째 단어와 j번째 단어의 가중치를 의미
*   weighted_edge[i][j] 가 0인 경우는 노드간 연결이 없음을 의미
*   모든 노드는 1로 초기화

In [45]:
import numpy as np
import math
vocab_len = len(vocab)

# 토큰별로 그래프 edge를 Matrix 형태로 생성
# 처음엔 0으로 생성. dtype=np.float32 안하면 기본적으로 np.float64로 생성된다.(메모리 사이즈 차이)
weighted_edge = np.zeros((vocab_len,vocab_len),dtype=np.float32)

# 각 토큰 노드별로 스코어 1로 초기화 하기전 0으로 선언
score = np.ones((vocab_len),dtype=np.float32)
print(score)

# coocurrence를 판단하기 위한 window 사이즈 설정
window_size = 2

# wincow_size를 3개 이상 으로 할 때 중복 작업이 발생한다.
# 중복 작업을 건너뛰기 위해 coocurrences를 한다(위치값 기억하기 위해.)
covered_coocurrences = [] 

# tokens = ['딸기', '바나나', '사과', '딸기', '파인애플']
for window_start in range(0, (len(tokens) - window_size + 1)):
    window = tokens[window_start : window_start + window_size]
    for i in range(window_size):
        for j in range(i+1, window_size):
            if window[i] in vocab2idx.keys() and window[j] in vocab:
                index_i, index_j = i + window_start, j + window_start

                if (index_i, index_j) not in covered_coocurrences:
                    # 각 토큰 노드연결 1로 초기화
                    weighted_edge[vocab2idx[window[i]]][vocab2idx[window[j]]] = 1
                    weighted_edge[vocab2idx[window[j]]][vocab2idx[window[i]]] = 1
                    covered_coocurrences.append((index_i, index_j))

for i in range(vocab_len): # 노드별 가중치 셋팅
    # 초기 스코어:1 이다. (스코어 = 스코어/해당 노드 연결된 노드수)
    row_sum = weighted_edge[i].sum()
    print(f"{i} : {row_sum}") # 그냥 값 볼라고 사용
    weighted_edge[i] = weighted_edge[i]/row_sum

weighted_edge


[1. 1. 1. 1.]
0 : 2.0
1 : 2.0
2 : 1.0
3 : 3.0


array([[0.        , 0.5       , 0.        , 0.5       ],
       [0.5       , 0.        , 0.        , 0.5       ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.33333334, 0.33333334, 0.33333334, 0.        ]], dtype=float32)

### 4) 각 노드의 score계산
각 노드와 연결된 weighted edge의 값을 합산

In [46]:
MAX_ITERATIONS = 50
d = 0.85
threshold = 0.0001

for iter in range(MAX_ITERATIONS):
    prev_score = np.copy(score)
    for i in range(vocab_len):
        summation = 0
        for j in range(vocab_len):
            summation += weighted_edge[j][i] * score[[1]j]
        score[i] = (1-d) + d*summation
    print("***** score *****")
    print(score)
    if np.sum(np.fabs(prev_score - score)) <= threshold:
        break
print("***** final *****")
print(score)

***** score *****
[0.85833335 0.798125   0.43333334 1.2223282 ]
***** score *****
[0.83552945 0.85142636 0.49632633 1.2888336 ]
***** score *****
[0.8770257 0.8879055 0.5151695 1.3379898]
***** score *****
[0.90645695 0.91434133 0.52909714 1.3735719 ]
***** score *****
[0.9277738 0.9334826 0.5391787 1.3993359]
***** score *****
[0.9432086  0.94734216 0.5464785  1.4179908 ]
***** score *****
[0.9543845 0.9573775 0.5517641 1.4314983]
***** score *****
[0.9624766 0.9646438 0.5555912 1.4412787]
***** score *****
[0.9683359 0.9699051 0.5583623 1.4483604]
***** score *****
[0.97257847 0.97371465 0.56036884 1.4534881 ]
***** score *****
[0.97565037 0.97647303 0.56182164 1.4572009 ]
***** score *****
[0.97787464 0.9784703  0.5628736  1.4598892 ]
***** score *****
[0.97948515 0.97991645 0.5636353  1.4618356 ]
***** score *****
[0.98065126 0.9809635  0.56418675 1.463245  ]
***** score *****
[0.9814956  0.98172176 0.5645861  1.4642656 ]
***** score *****
[0.98210704 0.9822708  0.56487525 1.465004

### 5) 핵심 단어 추출

In [47]:
sorted_index = np.flip(np.argsort(score),0)
# np.argsort(score)는 score의 인덱스를 값이 작은 순으로 정렬해 리스트로 반환한다.
# np.flip() 리스트 거꾸로 한다고 생각하면 편함.

print("\n=== 핵심키워드 ===")
n = 4 # 갯수제한
for i in range(0,n):
    print(str(idx2vocab[sorted_index[i]])+" : " + str(score[sorted_index[i]]))


=== 핵심키워드 ===
딸기 : 1.4668667
사과 : 0.98365426
바나나 : 0.98364776
파인애플 : 0.5656039


In [ ]:
sorted_index[0]

3

In [1]:
import requests 
from bs4 import BeautifulSoup
import re

def get_news_by_url(url):
  headers={"user-agent":"Mozilla/5.0"}
  res = requests.get(url, headers=headers)
  soup = BeautifulSoup(res.content, "html.parser")
  content = soup.select_one("#articleBodyContents").get_text().replace("\n", "")
  content = content.replace("// flash 오류를 우회하기 위한 함수 추가function _flash_removeCallback() {}", "")
  
  start_pos = re.search(r"\w+@\w+\.\w+(.\w+)?", content).start()
  content = content[:start_pos-1]
  return content

doc = get_news_by_url('https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=105&oid=018&aid=0004430108')
doc = re.sub("[^가-힣 \d]", " ", doc)
doc

'과기정통부  22일 유영민 장관 등 참석해 기념행사2021년까지 1516억원 투입  5100여종 데이터 구축민간 클라우드 통한 외부연계체계도   개방성 강화  이데일리 이재운 기자  국가 차원의 빅데이터 활용 시대가 열린다  새로운 산업 창출과 기존 산업의 변화에 이르는  혁신성장 을 위한 센터가 문을 연다  10개 분야에 걸쳐  데이터 경제 의 발전을 위한 정부의 청사진을 현실로 구현하는데 앞장선다는 계획이다 22일 과학기술정보통신부는 서울 중구 대한상공회의소에서 데이터 생태계 조성과 혁신 성장의 기반 마련을 위한  빅데이터 플랫폼 및 센터  출범식 행사를 개최했다  유영민 과기정통부 장관을 비롯해 노웅래 국회 과학기술정보방송통신위원회 위원장 등 300여명이 참가했다  10개 분야 100개 센터  3년간 1516억원 투입이미지  픽사베이빅데이터는 데이터 활용을 통해 혁신성장을 이루자는 문재인 정부의 경제 성장 핵심 요소중 하나다  문재인 대통령이 직접 올 들어 데이터 활용과 이에 따른 정보보호 보안 에 대한 중요성을 강조하기도 했다 이런 맥락 속에서 빅데이터센터는 공공과 민간이 협업해 활용도 높은 양질의 데이터를 생산 구축하고  플랫폼은 이를 수집 분석 유통하는 역할을 담당한다  과기정통부는 분야별 플랫폼 10개소와 이와 연계된 기관별 센터 100개소를 구축하는데 3년간 총 1516억원을 투입할 계획이며  올해 우선 640억원 규모의 사업을 추진하고 있다 대상 분야는  금융   카드   환경 한국수자원공사   문화 한국문화정보원   교통 한국교통연구원   헬스케어 국립암센터   유통 소비 매일방송   통신      중소기업 더존비즈온   지역경제 경기도청   산림 한국임업진흥원  등으로 현재 1차 공모를 통해 72개 빅데이터 센터를 선정했고  다음달 8일까지 2차 공모를 통해 28개를 추가 선정해 총 100개를 지원  운영할 계획이다  이를 통해 데이터 생태계를 혁신하고 기업의 경쟁력을 제고하는 역할을 수행한다 주요 활용 전략 사례를 보면 빅데이터 활용을 

### 1) 토큰화 (Tokenization)

분석 텍스트 정제

In [18]:
from konlpy.tag import Mecab
mecab = Mecab()

tokens = [ token for token in mecab.pos(doc) ]
nodes = [t[0] for t in tokens]
vocab = [t[0] for t in tokens if t[1] in ['NNG', 'NNP'] and len(t[0]) > 1]

print(nodes[:10])
print(vocab[:10])



['과기', '정통부', '22', '일', '유영민', '장관', '등', '참석', '해', '기념행사']
['과기', '정통부', '유영민', '장관', '참석', '기념행사', '투입', '여종', '데이터', '구축']


### 2) Unique한 토큰 목록 생성

그래프 생성을 위해서 Unique한 토큰 목록 생성

In [19]:
 vocab = list(set(vocab))

 vocab2idx = {vocab[i]:i for i in range(len(vocab))}
 idx2vocab = {i:vocab[i] for i in range(len(vocab))}

In [20]:

import numpy as np
import math

vocab_len = len(vocab2idx)

# 토큰별로 그래프 edge를 Matrix 형태로 생성
weighted_edge = np.zeros((vocab_len,vocab_len),dtype=np.float32)

# 각 토큰 노드별로 스코어 1로 초기화
score = np.ones((vocab_len),dtype=np.float32)

# coocurrence를 판단하기 위한 window 사이즈 설정
window_size = 3
covered_coocurrences = []

for window_start in range(len(nodes) - window_size + 1):
  window = nodes[window_start:window_start+window_size]
  for i in range(window_size):
    for j in range(i+1, window_size):
      if window[i] in vocab and window[j] in vocab:
        index_i = window_start + i
        index_j = window_start + j

        if (index_i, index_j) not in covered_coocurrences:
          weighted_edge[vocab2idx[window[i]]][vocab2idx[window[j]]] = 1
          weighted_edge[vocab2idx[window[j]]][vocab2idx[window[i]]] = 1
          covered_coocurrences.append((index_i, index_j))

for i in range(vocab_len):
  row_sum = weighted_edge[i].sum()
  weighted_edge[i] = weighted_edge[i]/row_sum if row_sum > 0 else 0

MAX_ITERATIONS = 50
d=0.85
threshold = 0.0001 #convergence threshold

for iter in range(MAX_ITERATIONS):
  prev_score = np.copy(score)

  for i in range(vocab_len):
    summation = 0
    for j in range(vocab_len):
      if weighted_edge[j][i] != 0:
        summation += weighted_edge[j][i] * prev_score[j]

    score[i] = (1 - d) * d*summation

  if np.sum(np.fabs(prev_score -  score)) <= threshold:
    break


sorted_index = np.flip(np.argsort(score), 0)

n = 5


print("\n=== 핵심키워드 ===")
for i in range(0,n):
    print(str(idx2vocab[sorted_index[i]])+" : " + str(score[sorted_index[i]]))


=== 핵심키워드 ===
데이터 : 7.405189e-07
센터 : 2.49831e-07
한국 : 2.0378042e-07
활용 : 1.9834519e-07
대한 : 1.9389464e-07


---

## 실습 2. 그래프 활용 

### 1) 토큰화 (Tokenization)

분석 텍스트 정제

### 2) 그래프 생성 (weighted edge 계산)

*   TextRank는 그래프 기반 모델
*   각 단어(토큰)은 그래프의 노드(vertex) 없음을 의미
*   모든 노드는 1로 초기화

In [21]:
import numpy as np
import math
import networkx as nx

# 윈도내 동시 등장한 토큰으로 그래프를 생성
def connect(vocab, nodes) :            
    window_size = 3

    edges = []
    for window_start in range(len(nodes) - window_size + 1):
      window = nodes[window_start: window_start + window_size]
      for i in range(window_size):
        for j in range(i + 1, window_size):
          if window[i] in vocab and window[j] in vocab:
            edges.append((window[i], window[j]))
      
    return edges


graph=nx.diamond_graph()
graph.clear() 
graph.add_nodes_from(vocab) #node 등록
graph.add_edges_from(connect(vocab, nodes)) #edge 연결    

### 3) 스코어 계산 및 핵심키워드 추출

In [22]:
scores = nx.pagerank(graph) #pagerank 계산

rank = sorted(scores.items(), key=lambda x: x[1], reverse=True) #score 역순 정렬
print("\n=== 핵심키워드 ===")
rank[:10]


=== 핵심키워드 ===


[('데이터', 0.04661070207125959),
 ('센터', 0.01676522225593208),
 ('대한', 0.012413811834749083),
 ('활용', 0.012361319397854266),
 ('한국', 0.012348645054362993),
 ('문화', 0.011604486043084145),
 ('경제', 0.011216010863143161),
 ('제공', 0.010178677656595398),
 ('구축', 0.009918384415693452),
 ('통신', 0.009755398667462636)]

---

## 실습 3. TextRank 핵심 구 추출

### 1) 불용어를 기준으로 구 추출

In [ ]:
phrases = []
phrase = " "


print(phrases)

['과기 정통부', '일 유영민 장관 등 참석', '기념행사', '년', '억 원 투입', '여종 데이터 구축 민간 클라우드', '외부 연계 체계', '개방', '강화', '데일리 이재운 기자', '국가 차원', '빅 데이터 활용 시대', '산업 창출', '기존 산업', '변화', '혁신', '장', '센터', '문', '개 분야', '데이터 경제', '발전', '정부', '청사진', '현실', '구현', '데', '계획', '일 과학 기술 정보 통신부', '서울 중구 대한 상공 회의소', '데이터 생태', '조성', '혁신 성장', '기반 마련', '빅 데이터 플랫 폼', '센터', '출범식 행사', '개최', '유영민 과기 정통부 장관', '노웅래 국회 과학 기술 정보 방송 통신 위원회 위원장 등', '명', '참가', '개 분야', '개 센터', '년 간', '억 원 투입 이미지', '픽사 베이 빅 데이터', '데이터 활용', '혁신', '장', '문재', '정부', '경제 성장 핵심 요소 중 하나', '문재인 대통령', '데이터 활용', '이', '정보 보호', '보안', '중요', '강조', '맥락 속', '빅 데이터 센터', '공공', '민간', '협업', '활용', '양질', '데이터', '생산', '구축', '플랫 폼', '이', '수집', '분석', '유통', '역할', '담당', '과기 정통부', '분야', '플랫 폼', '개소', '이', '연계', '기관', '센터', '개소', '구축', '데', '년', '억 원', '투입', '계획', '올해', '억 원 규모', '사업', '추진', '대상 분야', '금융', '카드', '환경', '한국 수자원 공사', '문화', '한국 문화 정보원', '교통', '한국 교통 연구원', '헬 스케어', '국립암센터', '유통', '소비', '매일 방송', '통신', '중소기업', '비즈', '지역 경제', '경기도 청', '산림', '한국 임업', '흥원', '등', '차 공모', '개 빅 데이터 

In [ ]:
unique_phrases = []


print(unique_phrases)

['과기 정통부', '일 유영민 장관 등 참석', '기념행사', '년', '억 원 투입', '여종 데이터 구축 민간 클라우드', '외부 연계 체계', '개방', '강화', '데일리 이재운 기자', '국가 차원', '빅 데이터 활용 시대', '산업 창출', '기존 산업', '변화', '혁신', '장', '센터', '문', '개 분야', '데이터 경제', '발전', '정부', '청사진', '현실', '구현', '데', '계획', '일 과학 기술 정보 통신부', '서울 중구 대한 상공 회의소', '데이터 생태', '조성', '혁신 성장', '기반 마련', '빅 데이터 플랫 폼', '출범식 행사', '개최', '유영민 과기 정통부 장관', '노웅래 국회 과학 기술 정보 방송 통신 위원회 위원장 등', '명', '참가', '개 센터', '년 간', '억 원 투입 이미지', '픽사 베이 빅 데이터', '데이터 활용', '문재', '경제 성장 핵심 요소 중 하나', '문재인 대통령', '이', '정보 보호', '보안', '중요', '강조', '맥락 속', '빅 데이터 센터', '공공', '민간', '협업', '활용', '양질', '데이터', '생산', '구축', '플랫 폼', '수집', '분석', '유통', '역할', '담당', '분야', '개소', '연계', '기관', '억 원', '투입', '올해', '억 원 규모', '사업', '추진', '대상 분야', '금융', '카드', '환경', '한국 수자원 공사', '문화', '한국 문화 정보원', '교통', '한국 교통 연구원', '헬 스케어', '국립암센터', '소비', '매일 방송', '통신', '중소기업', '비즈', '지역 경제', '경기도 청', '산림', '한국 임업', '흥원', '등', '차 공모', '개 빅 데이터 센터', '선정', '다음 달', '일', '개', '추가 선정', '지원', '운영', '데이터 생태계', '기업', '경쟁력', '제고', '수행', '주요 활용 전략', '사례', '빅 데이

### 2) 각 구의 Score 계산

앞서 산출한 각 단어별 점수를 합산

In [ ]:
vocabs = dict((r[0][0],r[1]) for r in rank)
phrase_scores = []
keywords = []


Keyword: '과기 정통부', Score: 0.01124933498027082
Keyword: '일 유영민 장관 등 참석', Score: 0.013047761313401546
Keyword: '기념행사', Score: 0.0022034464344388585
Keyword: '년', Score: 0
Keyword: '억 원 투입', Score: 0.003215471038656386
Keyword: '여종 데이터 구축 민간 클라우드', Score: 0.06857882292392038
Keyword: '외부 연계 체계', Score: 0.01653296999059789
Keyword: '개방', Score: 0.007608411089591418
Keyword: '강화', Score: 0.0022598290466079364
Keyword: '데일리 이재운 기자', Score: 0.016337448780957005


### 3) 각 구를 Score로 정렬하여 핵심 구 추출

In [ ]:
sorted_index = np.flip(np.argsort(phrase_scores),0)

keywords_num = 10

print("Keywords:\n")

for i in range(0,keywords_num):
    print(str(keywords[sorted_index[i]])+", ")

Keywords:

여종 데이터 구축 민간 클라우드, 
빅 데이터 플랫 폼, 
빅 데이터 센터, 
개 빅 데이터 센터, 
빅 데이터 활용 시대, 
민간 사이 데이터 파일 형식 등, 
빅 데이터 활용, 
픽사 베이 빅 데이터, 
여종 데이터 구축, 
데이터 경제, 




---



## 실습 4. gensim 활용

In [ ]:
from gensim.summarization import keywords
keywords(doc, words=5).split('\n')

['데이터', '데이터를', '계획이다', '빅데이터', '문재인']

In [ ]:
keywords?

https://github.com/lovit/KR-WordRank