# 함수응용 실습 01

In [1]:
def allindex(list_name,find_num):
    return_list = []
    for i in range(len(list_name)):
        if list_name[i] == find_num:
            return_list.append(i)
    return return_list
    
lis = [1,2,3,1,4,2,1]
print(allindex(lis,1))
# print(lis.count(1))

[0, 3, 6]


# 실습 02

In [3]:
def calc(*args):
    temp = 0
    for i in range(1,len(args)):
        if args[0] == '+':
            temp += args[i]
        elif args[0] == '*':
            if i == 1:
                temp += 1
            temp *= args[i]
    return temp
print(calc('+',1,2,3,4,5))
print(calc('*',1,2,3,4,5))

15
120


# 실습 03 
### 재귀함수
아직 익숙하지 않아서 어려움..

In [3]:
# 재귀함수
def fac(n):
    if n == 1 :
        return 1
    else :
        return fac(n-1)*n
print(fac(5))

120


In [4]:
# (1)
def f_sum(n):
    if n == 1:
        return 1
    return f_sum(n-1)+n



print(f_sum(5))   

15


In [12]:
# (2)
def f_number(n):
    print()
    print(n,"--------")
    print()
    if len(str(n))==1:
        return n
    print(str(n)[-1:],"--------!!!!!!!!!!!")
    return str(n)[-1:]+"\n"+f_number(str(n)[:-1])
        
print(f_number(1234))
print()
print(str(1234)[-1:])


1234 --------

4 --------!!!!!!!!!!!

123 --------

3 --------!!!!!!!!!!!

12 --------

2 --------!!!!!!!!!!!

1 --------

4
3
2
1

4


# 실습 04
### 람다

In [21]:
number = [0, -11, 31, 22, -11, 33, -44, -55]
for i in range(len(number)):
    
    print(len(number), i)
    if number[i] < 0:
        number.remove(number[i])
    else :
        pass
print(number)

8 0
8 1
7 2
7 3
6 4
5 5


IndexError: list index out of range

In [25]:
number = [0, -11, 31, 22, -11, 33, -44, -55]
for i in number:
    if i < 0:
        number.remove(i)
    else :
        pass
    print(number, i)
# print(number)

[0, -11, 31, 22, -11, 33, -44, -55] 0
[0, 31, 22, -11, 33, -44, -55] -11
[0, 31, 22, -11, 33, -44, -55] 22
[0, 31, 22, 33, -44, -55] -11
[0, 31, 22, 33, -55] -44


In [6]:
#(1)
number = [12,32,55,12,32,4,86,50]
new_number = list(map(lambda x:'합격' if x > 60 else '불합격' if x < 50 else '대기',number))
print(new_number)

['불합격', '불합격', '대기', '불합격', '불합격', '불합격', '합격', '대기']


In [80]:
#(2)
files = ["memo.txt", "1.jpg", "32.png", "23.jpg", "223.jpg"]
files = (list(filter(lambda x:x.find('jpg') != -1,files)))
print(files)
# x.find('jpg')는 x에'jpg'가 들어 있다면 해당 인덱스를 반환한다. 즉, 위에선 1,3,4 를 반환한다 
# 하지만 'jpg'가 들어있지 않다면 -1을 반환한다.
# 이를 통해 x.find('jpg') != -1이 True일때만 filter을 통해 'jpg'가 있는 것들만 들어간다. 

['1.jpg', '23.jpg', '223.jpg']


In [81]:
files = ["memo.txt", "1.jpg", "32.png", "23.jpg", "223.jpg"]
files = (list(filter(lambda x:x.find('jpg') == True,files)))
print(files)
# x.find('jpg')는 -1또는 조건을 만족하는 문자열의 인덱스를 반환한다.
# 따라서 x.find('jpg') == True 의 결과는 항상 False가 나오므로
# filter에서 빈 리스트인 []가 나온다.

[]


In [60]:
files = ["memo.txt", "1.jpg", "32.png", "23.jpg", "223.jpg"]
for i in files:
    print(i)
    print(i.find('jpg'))

memo.txt
-1
1.jpg
2
32.png
-1
23.jpg
3
223.jpg
4


# 클래스 실습 01

In [8]:
class Car:
    car_count = 0
    
    def __init__(self, name, cc, age):
        self.name = name
        self.cc = cc
        self.age = age
        Car.car_count += 1

    def car_size(self):
        if self.cc > 2000:
            print('{0}cc 대형차'.format(self.cc))
        elif self.cc > 999:
            print('{0}cc 중형차'.format(self.cc))
        else:
            print('{0}cc 소형차'.format(self.cc))
    
    def car_age(self):
        print("연식은 {0}식 입니다.".format(self.age))

    def carCount(self):
        print("등록된 차량은 {0}대 입니다.".format(Car.car_count))

In [9]:
my_car = Car("ace", 1000, 1994)

In [10]:
my_car.carCount()
my_car.car_size()
my_car.car_age()

등록된 차량은 1대 입니다.
1000cc 중형차
연식은 1994식 입니다.


In [95]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
y = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
for i in range(len(x)):
    print("{0}\t\t{1}".format(x[i], y[i]))
print(x+y)
print(x.dot(y))

[1 2 3]		[10 20 30]
[4 5 6]		[40 50 60]
[7 8 9]		[70 80 90]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [96]:
print(np.linspace(1,20,30))

[ 1.          1.65517241  2.31034483  2.96551724  3.62068966  4.27586207
  4.93103448  5.5862069   6.24137931  6.89655172  7.55172414  8.20689655
  8.86206897  9.51724138 10.17241379 10.82758621 11.48275862 12.13793103
 12.79310345 13.44827586 14.10344828 14.75862069 15.4137931  16.06896552
 16.72413793 17.37931034 18.03448276 18.68965517 19.34482759 20.        ]


In [127]:
temp = np.random.choice(100, size=(2,10,10)) # 1~100의 랜덤한 숫자로 채운 10*10 배열 2개 생성
temp = np.where(temp >= 50, temp, 1) # 넘파이 배열 내 50이상인 값을 1로 변환
temp = np.where(temp < 50, temp, 2) # 넘파이 배열 내 50미만인 값을 2로 변환
temp_2 = np.split(temp[1],2) # 가로로 자르고 2개로 반환 (위=[0], 아래=[1])
temp_3 = np.split(temp_2[1],2, axis=1) # 세로로 자르고 2개로 반환 (왼쪽=[0], 오른쪽=[1])
print("{0}\n\n{1}\n\n{2}".format(temp[0], temp[1], temp_3[1]))

[[1 2 2 2 1 2 1 1 1 1]
 [2 2 1 1 1 1 1 1 2 1]
 [1 2 2 2 2 2 1 2 2 2]
 [1 1 2 2 2 1 1 2 1 2]
 [2 2 2 1 2 1 1 1 1 2]
 [2 2 1 2 2 2 2 1 2 2]
 [2 1 2 2 1 2 1 1 2 2]
 [1 2 2 2 1 2 1 2 1 1]
 [2 1 2 1 1 2 1 1 1 2]
 [1 2 2 1 1 1 1 2 1 1]]

[[2 1 1 2 2 2 2 1 2 2]
 [2 2 2 1 2 1 1 1 1 2]
 [2 1 2 1 2 2 2 2 1 2]
 [2 2 1 2 1 2 1 2 2 1]
 [1 2 1 2 1 1 1 1 2 2]
 [1 1 2 2 1 1 2 1 1 2]
 [1 1 1 2 1 1 2 2 2 2]
 [2 2 2 1 1 1 1 1 1 1]
 [2 2 2 1 2 2 1 1 1 1]
 [2 2 1 1 2 2 1 2 2 1]]

[[1 2 1 1 2]
 [1 2 2 2 2]
 [1 1 1 1 1]
 [2 1 1 1 1]
 [2 1 2 2 1]]


In [115]:
x = np.arange(16).reshape(4,4)
print(x)
np.split(x,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]