In [4]:
import numpy as np

In [9]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]
# 행렬합 구하기
print("np.array(matrix_1) + np.array(matrix_2) : \n{0}".format(np.array(matrix_1) + np.array(matrix_2)))
# matrix_1에 숫자 1씩 더하기
print("np.array(matrix_1) + 1 : \n{0}".format(np.array(matrix_1) + 1))

np.array(matrix_1) + np.array(matrix_2) : 
[[ 6  8]
 [10 12]]
np.array(matrix_1) + 1 : 
[[2 3]
 [4 5]]


### 넘파이 리스트 ndarray만들기

In [15]:
print("np.array([1, 2, 3, 4]) : \n{0}".format(np.array([1, 2, 3, 4])))
print("np.float32([1, 2, 3, 4]) : \n{0}".format(np.float32([1, 2, 3, 4])))
print("np.uint(32) : \n{0}".format(np.uint(32)))
print("np.array([1, 2, 3, 4], dtype=np.float32) : \n{0}".format(np.array([1, 2, 3, 4], dtype=np.float32)))

np.array([1, 2, 3, 4]) : 
[1 2 3 4]
np.float32([1, 2, 3, 4]) : 
[1. 2. 3. 4.]
np.uint(32) : 
32
np.array([1, 2, 3, 4], dtype=np.float32) : 
[1. 2. 3. 4.]


In [16]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
x = np.int32(x)
print(x.dtype)
print("np.issubdtype(x.dtype, np.int32) : \n{0}".format(np.issubdtype(x.dtype, np.int32)))


int32
np.issubdtype(x.dtype, np.int32) : 
True


### 다차원 nbarray
- ndarray.shape #행렬구조 ex (2, 3)
- ndarray.ndim #몇차원인지
- ndarray.size # 원소의 개수

In [17]:
x = np.array(1)
print(x.shape) # ()
print(x.ndim) # 0
print(x.size) # 1

()
0
1


In [18]:
x = np.array([1,2])
print(x.shape) # (2,)
print(x.ndim) # 1
print(x.size) # 2

(2,)
1
2


In [19]:
x = np.array([[1, 2, 3],[4, 5, 6]])
print(x.shape) # (2, 3)
print(x.ndim) # 2
print(x.size) # 6

(2, 3)
2
6


### arange
> range와 비슷하다.
> - np.arange(시작값, 끝값, 증가값)

In [21]:
x = np.arange(10)
print(x)
print()
x = np.arange(10.0)
print(x)
print()
x = np.arange(1, 10, 2)
print(x)
print()
x = np.arange(1, 10, 0.5)
print(x)
print()
x = np.arange(10, 1, -0.5)
print(x)
print()

[0 1 2 3 4 5 6 7 8 9]

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

[1 3 5 7 9]

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]



### linspace
- 균일한 간격으로 리스트 크기만큼 리스트 생성
> np.linspace(시작값, 끝값, 벡터크기) 끝값 포함
> np.linspace(시작값, 끝값, 벡터크기, endpoint=False) 끝값 미포함

In [22]:
x = np.linspace(1, 20, 5)
print(x)
print()

x = np.linspace(1, 20, 10, endpoint=False)
print(x)
print()

[ 1.    5.75 10.5  15.25 20.  ]

[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]



### reshape
- 데이터를 유지하면서 차원의 형태를 변경

In [23]:
# ndarray.reshape(3, 3)
x = np.arange(9).reshape(3, 3)
print(x) # 2차원

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
# ndarray.reshape(2, 3, 4)
x = np.arange(24).reshape(2, 3, 4)
print(x) # 2차원

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [25]:
# ndarray.reshape(2, 2, 2, 2)
x = np.arange(16).reshape(2, 2, 2, 2)
print(x) # 4차원

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [26]:
# np.array([[1,2],[3,4],[5,6]]).reshape(2,3)
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.reshape(2,3)) # 데이터를 유지하고 형태변경

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [27]:
# -1 일경우 자동으로 맞춰서 생성 ndarray.reshape(3,-1)
x = np.arange(9).reshape(3, -1)
print(x) #개수에 맞춰 생성

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### slicing
- a[처음값:끝값:증가값]

- 1차원뿐만 아니라 다차원 슬라이싱 가능( x[1:3, 1:3], x[:3,:3,:3])

In [29]:
# 1차원 슬라이싱
x = np.arange(20)
print(x[1:3])

[1 2]


In [30]:
# 2차원 슬라이싱
x = np.arange(20).reshape(4,5)
print(x)
print(x[1:3])
print(x[1:3, 1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6  7]
 [11 12]]


In [20]:
# 3차원 슬라이싱
x = np.arange(30).reshape(2,5,3)
print(x)
print(x[:,3:5,1:3])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[[10 11]
  [13 14]]

 [[25 26]
  [28 29]]]


### indexing & boolean indexing
- 다차원 리스트 접근 (x[1][1], x[1,1])

- 한번에 여러 값 인덱싱 (x[[1,1],[1,2]])

- indexing에 비교, 논리연산자 사용가능 (!, &, |)

In [5]:
a = np.arange(20).reshape(4, 5)
# indexing
print(a[1][1])
print(a[1,1])
print(a[[1,1],[1,2]])

6
6
[6 7]


In [6]:
# indexing에 비교, 논리연산자 사용가능 (!, &, |)
# boolean indexing
print("a > 3 : \n{0}\n".format(a > 3))
print("a[a > 3] : \n{0}\n".format(a[a > 3]))
print("a[a == 1] : \n{0}\n".format(a[a == 1]))
print("a[~(a == 1)] : \n{0}\n".format(a[~(a == 1)]))
print("a[(a > 3)&(a < 8)] : \n{0}\n".format(a[(a > 3)&(a < 8)]))


a > 3 : 
[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

a[a > 3] : 
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

a[a == 1] : 
[1]

a[~(a == 1)] : 
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

a[(a > 3)&(a < 8)] : 
[4 5 6 7]



### random
- 난수가 들어가 있는 다양한 형태의 데이터

In [45]:
print(np.random.rand(5,5))
print("\n-------------\n")
print(np.random.randint(1, 10))

[[0.79061875 0.06700963 0.69132584 0.05047915 0.4531828 ]
 [0.19952966 0.56175431 0.17134663 0.66553658 0.51540186]
 [0.10343806 0.23015693 0.90938986 0.03265727 0.56730575]
 [0.05981354 0.79200319 0.59864648 0.07414624 0.27241413]
 [0.89255515 0.30329944 0.62982341 0.59115511 0.55551488]]

-------------

2


In [44]:
print(np.random.randint(1, 10, size=(5)))
print("\n-------------\n")
print(np.random.randint(1, 10, size=(5,5)))
print("\n-------------\n")
print(np.random.randint(1, 10, size=(2,5,5)))

[2 4 7 6 6]

-------------

[[6 2 9 9 9]
 [2 4 6 1 9]
 [4 4 5 3 1]
 [5 2 2 5 6]
 [6 5 7 3 5]]

-------------

[[[7 2 6 3 6]
  [8 4 6 7 4]
  [3 8 4 4 5]
  [7 8 7 3 6]
  [7 3 6 6 6]]

 [[7 2 6 4 2]
  [9 5 1 7 3]
  [8 1 2 6 9]
  [7 2 7 4 1]
  [1 8 5 9 4]]]


In [48]:
# 주어진 리스트 안에 있는 숫자 뽑기
np.random.choice(100, size=(3, 4))
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.random.choice(x, size=(2, 2))

array([[6, 4],
       [5, 5]])

### 특이한 형태의 배열

In [51]:
# 1로 채워진 배열
print(np.ones([5,5]))
# 0으로 채워진 배열
print(np.zeros([5,5]))
# 단위행렬(행렬곱을 했을때 자기자신이 나오는)
print(np.eye(5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [60]:
test_np = np.random.randint(1, 10, size=(5,5))
print("행 기준으로 펼치기 : \n{0}".format(test_np.ravel()))
print("행 기준으로 펼치기 : \n{0}".format(test_np.ravel(order='C')))
print("\n열 기준으로 펼치기 : \n{0}".format(test_np.ravel(order='F')))

행 기준으로 펼치기 : 
[3 8 8 9 2 7 6 9 1 4 1 4 2 3 1 1 5 5 9 4 5 3 2 9 4]
행 기준으로 펼치기 : 
[3 8 8 9 2 7 6 9 1 4 1 4 2 3 1 1 5 5 9 4 5 3 2 9 4]

열 기준으로 펼치기 : 
[3 7 1 1 5 8 6 4 5 3 8 9 2 5 2 9 1 3 9 9 2 4 1 4 4]


### concatenate
- 배열을 연결 ```np.concatenate([x, y])```

In [68]:
x = np.arange(1, 4)
y = np.arange(4, 7)
print("행 기준으로 연결 : \n{0}\n-----------------".format(np.concatenate([x, y])))

# 열을 기준으로 np.concatenate([x, y], axis=1)
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)
print("\nx : \n{0}".format(x))
print("\ny : \n{0}".format(y))
print("\n행 기준으로 연결 : \n{0}".format(np.concatenate([x, y])))
print("\n열 기준으로 연결 : \n{0}".format(np.concatenate([x, y], axis=1)))

행 기준으로 연결 : 
[1 2 3 4 5 6]
-----------------

x : 
[[0 1 2 3 4]
 [5 6 7 8 9]]

y : 
[[10 11 12 13 14]
 [15 16 17 18 19]]

행 기준으로 연결 : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

열 기준으로 연결 : 
[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


### split
- 배열을 분해 ```np.split(x, 4)```

In [72]:
x = np.arange(12)
print("x : \n{0}".format(x))
print("\n{0}\n".format(np.split(x, 4)))
x = np.arange(16).reshape(4, 4)
print("\nx : \n{0}".format(x))
print("\n{0}\n".format(np.split(x, 2)))

# 열을 기준으로 np.split(x, 2, axis=1)
x = np.arange(16).reshape(4, 4)
print("\nx : \n{0}".format(x))
print("\n열을 기준으로 np.split(x, 2, axis=1) :\n{0}".format(np.split(x, 2, axis=1)))

x : 
[ 0  1  2  3  4  5  6  7  8  9 10 11]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


x : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


x : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

열을 기준으로 np.split(x, 2, axis=1) :
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


### 연산 및 집계함수

In [93]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4).reshape(2, 2)

print(x.dot(y)) # 행렬곱

[[ 2  3]
 [ 6 11]]


In [94]:
print(np.transpose(x)) # 전치행렬

[[0 2]
 [1 3]]


In [95]:
print(np.linalg.inv(x)) # 역행렬

[[-1.5  0.5]
 [ 1.   0. ]]


In [96]:
print(np.linalg.det(x)) # 행렬식

-2.0


In [97]:
print(np.mean(x)) # 평균

1.5


In [98]:
print(np.median(x)) # 중간값

1.5


In [99]:
print(np.std(x)) # 표준편차

1.118033988749895


In [100]:
print(np.var(x)) # 분산

1.25


In [101]:
print(np.sum(x)) # 합

6


In [105]:
print(np.sum(x, axis=1)) # 합, 축변경

[1 5]


In [106]:
print(np.cumsum(x)) # 누적합

[0 1 3 6]


In [107]:
print(np.cumprod(x)) # 누적곱

[0 0 0 0]


In [108]:
print(np.min(x)) # 최소값

0


In [109]:
print(np.argmin(x)) # 최소값 위치

0


In [110]:
print(np.argmax(x)) # 최대값 위치

3


In [111]:
print(np.any(x > 4)) # 하나라도 참이어야 참

False


In [112]:
print(np.all(x > 4)) # 모든 요소가 참이어야 참

False


In [113]:
print(np.where(x > 4)) # 조건에 맞는위치

(array([], dtype=int64), array([], dtype=int64))


In [114]:
print(np.where(x > 4, x, -100)) # 조건, True 일경우, False 일경우

[[-100 -100]
 [-100 -100]]


# 실습 01
x = [1,2,3,4,5,6,7,8,9]
y = [10,20,30,40,50,60,70,80,90]
위의 배열로 Numpy를 사용해 3 X 3 행렬을 만든 뒤 행렬합과 행렬곱을 구해주세요

In [25]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
y = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
for i in range(len(x)):
    print("{0}\t\t{1}".format(x[i], y[i]))
print("\n행렬합 : \n{0}".format(x+y))
print("\n행렬곱 : \n{0}".format(x.dot(y)))

[1 2 3]		[10 20 30]
[4 5 6]		[40 50 60]
[7 8 9]		[70 80 90]

행렬합 : 
[[11 22 33]
 [44 55 66]
 [77 88 99]]

행렬곱 : 
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


# 실습 02
1에서 20 사이의 균일한 간격으로 30개의 숫자를 만들고 모든 값에 숫자 10을 더해주세요

In [26]:
print(np.linspace(1,20,30)+10)

[11.         11.65517241 12.31034483 12.96551724 13.62068966 14.27586207
 14.93103448 15.5862069  16.24137931 16.89655172 17.55172414 18.20689655
 18.86206897 19.51724138 20.17241379 20.82758621 21.48275862 22.13793103
 22.79310345 23.44827586 24.10344828 24.75862069 25.4137931  26.06896552
 26.72413793 27.37931034 28.03448276 28.68965517 29.34482759 30.        ]


# 실습 3
1 ~ 100 까지 난수가 들어있는 2 X 10 X 10 배열을 만들고
50보다 크거나 같은 값은 1, 50보다 작은 값은 2로 변환하고 
2번째 배열에 '+' 모양으로 선을 그어 5x5사이즈 배열로 분할했을 때 오른쪽 아래의 5x5배열만 출력하세요

In [61]:
temp = np.random.choice(101, size=(2,10,10)) # 1~100의 랜덤한 숫자로 채운 10*10 배열 2개 생성
temp = np.where(temp >= 50, 1, 2) # 넘파이 배열 내 50이상인 값을 1로 변환 50 미만이라면 2로 변환
#temp = np.where('조건', 'True 일때 사용할 값 (위에서 2 대신 temp쓰면 원래값 쓰겠다는 것.)', 'false일때 사용할 값')

In [62]:
temp_2 = np.split(temp[1],2) # 가로로 자르고 2개로 반환 (위=[0], 아래=[1])
temp_3 = np.split(temp_2[1],2, axis=1) # 세로로 자르고 2개로 반환 (왼쪽=[0], 오른쪽=[1])
print(temp_3[1])

[[1 1 1 2 1]
 [1 2 1 1 2]
 [1 1 2 1 1]
 [2 1 1 2 2]
 [1 1 1 1 2]]


In [63]:
print(temp[1,5:,5:])

[[1 1 1 2 1]
 [1 2 1 1 2]
 [1 1 2 1 1]
 [2 1 1 2 2]
 [1 1 1 1 2]]


In [32]:
x = np.arange(16).reshape(4,4)
print(x)
np.split(x,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]